CREATE TABLE Team (
    TeamID INTEGER PRIMARY KEY AUTOINCREMENT,
    TeamName TEXT NOT NULL,
    FoundedYear INTEGER NOT NULL,
    City TEXT NOT NULL,
    StadiumID INTEGER NOT NULL,
    FOREIGN KEY (StadiumID) REFERENCES Stadium(StadiumID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TeamMember (
    PersonID INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    BirthDate DATE NOT NULL,
    Nationality TEXT NOT NULL,
    Salary INTEGER NOT NULL,
    TeamID INTEGER NOT NULL,
    FOREIGN KEY (TeamID) REFERENCES Team(TeamID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Coach (
    CoachID INTEGER PRIMARY KEY AUTOINCREMENT,
    MemberID INTEGER NOT NULL,
    Role TEXT NOT NULL,
    FOREIGN KEY (MemberID) REFERENCES TeamMember(PersonID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Player (
    PlayerID INTEGER PRIMARY KEY AUTOINCREMENT,
    MemberID INTEGER NOT NULL,
    Position TEXT NOT NULL,
    JerseyNumber INTEGER NOT NULL,
    FOREIGN KEY (MemberID) REFERENCES TeamMember(PersonID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Match (
    MatchID INTEGER PRIMARY KEY AUTOINCREMENT,
    MatchDate DATE NOT NULL,
    StadiumID INTEGER NOT NULL,
    CompetitionID INTEGER NOT NULL,
    HomeScore INTEGER NOT NULL,
    AwayScore INTEGER NOT NULL,
    HomeTeamID INTEGER NOT NULL,
    AwayTeamID INTEGER NOT NULL,
    FOREIGN KEY (StadiumID) REFERENCES Stadium(StadiumID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (CompetitionID) REFERENCES Competition(CompetitionID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (HomeTeamID) REFERENCES Team(TeamID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (AwayTeamID) REFERENCES Team(TeamID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Stadium (
    StadiumID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    City TEXT NOT NULL,
    Capacity INTEGER NOT NULL
);

CREATE TABLE Competition (
    CompetitionID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Season INTEGER NOT NULL
);

CREATE TABLE PlayerMatch (
    PlayerMatchID INTEGER PRIMARY KEY AUTOINCREMENT,
    PlayerID INTEGER NOT NULL,
    MatchID INTEGER NOT NULL,
    MinutesPlayed INTEGER NOT NULL,
    Goals INTEGER NOT NULL,
    Assists INTEGER NOT NULL,
    YellowCards INTEGER NOT NULL,
    RedCards INTEGER NOT NULL,
    FOREIGN KEY (PlayerID) REFERENCES Player(PlayerID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MatchID) REFERENCES Match(MatchID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
